spring:
  application:
    name: groot
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8080
  servlet:
    contextPath: /groot
grpc:
  port: 6565
  enable-reflection: true
  shutdownGrace: 30



